require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PeepsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Peep. As you add validations to Peep, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PeepsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all peeps as @peeps" do
      peep = Peep.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:peeps)).to eq([peep])
    end
  end

  describe "GET #show" do
    it "assigns the requested peep as @peep" do
      peep = Peep.create! valid_attributes
      get :show, {:id => peep.to_param}, valid_session
      expect(assigns(:peep)).to eq(peep)
    end
  end

  describe "GET #new" do
    it "assigns a new peep as @peep" do
      get :new, {}, valid_session
      expect(assigns(:peep)).to be_a_new(Peep)
    end
  end

  describe "GET #edit" do
    it "assigns the requested peep as @peep" do
      peep = Peep.create! valid_attributes
      get :edit, {:id => peep.to_param}, valid_session
      expect(assigns(:peep)).to eq(peep)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Peep" do
        expect {
          post :create, {:peep => valid_attributes}, valid_session
        }.to change(Peep, :count).by(1)
      end

      it "assigns a newly created peep as @peep" do
        post :create, {:peep => valid_attributes}, valid_session
        expect(assigns(:peep)).to be_a(Peep)
        expect(assigns(:peep)).to be_persisted
      end

      it "redirects to the created peep" do
        post :create, {:peep => valid_attributes}, valid_session
        expect(response).to redirect_to(Peep.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved peep as @peep" do
        post :create, {:peep => invalid_attributes}, valid_session
        expect(assigns(:peep)).to be_a_new(Peep)
      end

      it "re-renders the 'new' template" do
        post :create, {:peep => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested peep" do
        peep = Peep.create! valid_attributes
        put :update, {:id => peep.to_param, :peep => new_attributes}, valid_session
        peep.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested peep as @peep" do
        peep = Peep.create! valid_attributes
        put :update, {:id => peep.to_param, :peep => valid_attributes}, valid_session
        expect(assigns(:peep)).to eq(peep)
      end

      it "redirects to the peep" do
        peep = Peep.create! valid_attributes
        put :update, {:id => peep.to_param, :peep => valid_attributes}, valid_session
        expect(response).to redirect_to(peep)
      end
    end

    context "with invalid params" do
      it "assigns the peep as @peep" do
        peep = Peep.create! valid_attributes
        put :update, {:id => peep.to_param, :peep => invalid_attributes}, valid_session
        expect(assigns(:peep)).to eq(peep)
      end

      it "re-renders the 'edit' template" do
        peep = Peep.create! valid_attributes
        put :update, {:id => peep.to_param, :peep => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested peep" do
      peep = Peep.create! valid_attributes
      expect {
        delete :destroy, {:id => peep.to_param}, valid_session
      }.to change(Peep, :count).by(-1)
    end

    it "redirects to the peeps list" do
      peep = Peep.create! valid_attributes
      delete :destroy, {:id => peep.to_param}, valid_session
      expect(response).to redirect_to(peeps_url)
    end
  end

end
